connect 'jdbc:derby://localhost:1527/sun-appserv-samples;user=APP;password=APP;create=true';
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Channing','Reuben','est.Nunc.laoreet@nec.edu'),( 'Wayne','Uriah','dolor@facilisi.com'),( 'Jenna','Noble','mi@Phasellusvitaemauris.com'),( 'Susan','Calvin','Aenean@arcuvel.edu'),( 'Wylie','Clinton','dolor.quam@condimentumegetvolutpat.org'),( 'Jermaine','Warren','Ut@velit.com'),( 'Jaime','Paki','Praesent@Donec.org'),( 'Anastasia','Colt','et.malesuada@auctorullamcorpernisl.com'),( 'Rhonda','Colin','libero.Integer@tortorNunccommodo.ca'),( 'Chaney','Peter','pellentesque@Nunc.edu');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Hammett','Patrick','Nunc.laoreet@eu.org'),( 'Hilda','Colin','sed@velarcu.net'),( 'Lacota','Dominic','et@facilisisnon.co.uk'),( 'Clarke','Alan','orci@nulla.co.uk'),( 'Katelyn','Chester','Mauris.ut@faucibusorciluctus.org'),( 'Ora','Caleb','vel.mauris.Integer@montesnascetur.edu'),( 'Rhoda','Drew','lectus.quis.massa@luctusipsum.co.uk'),( 'Ignacia','Buckminster','risus@sem.org'),( 'Cailin','Otto','Nulla@Nullamvitae.net'),( 'Ora','Malcolm','velit@maurisMorbi.org');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Kasimir','Grant','iaculis.odio.Nam@mollisneccursus.com'),( 'Colin','Kadeem','velit@ipsumdolorsit.edu'),( 'Brenna','Dolan','Mauris.molestie.pharetra@sociis.com'),( 'Hanna','Fritz','sem@veliteu.edu'),( 'Zephr','Octavius','in.consequat@liberonecligula.org'),( 'Zephania','Thor','a.mi.fringilla@necmetusfacilisis.edu'),( 'Vivian','Perry','neque.Nullam.nisl@doloregestasrhoncus.edu'),( 'Ariel','Kibo','nunc.Quisque@elita.org'),( 'James','Ronan','Donec@tempuslorem.org'),( 'Brett','Fuller','sed.consequat@aclibero.co.uk');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Colleen','Berk','lorem.semper@atortor.net'),( 'Katell','Igor','commodo@felis.edu'),( 'Brielle','Murphy','Nam.porttitor@nequesed.edu'),( 'Autumn','Craig','lacus@vestibulum.edu'),( 'Brady','Ivan','Nullam.feugiat@ut.edu'),( 'Kessie','Ryan','Nulla.facilisis@diamPellentesquehabitant.ca'),( 'Helen','Thaddeus','sed.tortor@vitaediamProin.co.uk'),( 'Kamal','Clarke','arcu@adipiscinglacusUt.co.uk'),( 'Bryar','Elijah','mattis.Cras.eget@dui.org'),( 'Olympia','Armand','Phasellus@Integervulputate.org');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Fitzgerald','Thane','eu@tempus.co.uk'),( 'Reagan','Clinton','lorem.sit.amet@Donec.edu'),( 'Dakota','Victor','sed.pede.nec@aliquam.co.uk'),( 'Coby','Micah','egestas.blandit@dictumeuplacerat.net'),( 'Geoffrey','Emmanuel','arcu.Nunc@elitsed.com'),( 'Zeus','Dante','sapien@facilisis.co.uk'),( 'Hakeem','Brett','vulputate.velit@lectuspede.edu'),( 'Gregory','Brett','Nam.porttitor@tellusnonmagna.org'),( 'Alexa','Orson','neque@Sedeu.co.uk'),( 'Gwendolyn','Jacob','a.mi@iaculisnec.net');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Pamela','Nolan','amet.orci.Ut@id.org'),( 'Karyn','Murphy','lacus@sapienimperdiet.ca'),( 'Lani','Dolan','augue.eu.tempor@commodoat.co.uk'),( 'Jaquelyn','Upton','eu@loremipsum.com'),( 'Ifeoma','Burke','volutpat@Utsagittislobortis.net'),( 'Rae','Kasimir','tellus.id.nunc@Aliquamtinciduntnunc.co.uk'),( 'Maggie','Arthur','vestibulum@vitaepurus.co.uk'),( 'Summer','Kato','adipiscing.fringilla.porttitor@arcuVivamussit.org'),( 'Camille','Ulric','eleifend.egestas@rutrumloremac.ca'),( 'Sybil','Talon','elit.sed.consequat@augueeutellus.edu');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Aurelia','Knox','ipsum.cursus.vestibulum@nislMaecenas.com'),( 'Chelsea','Kenneth','enim.diam@bibendum.org'),( 'Jennifer','Drake','Nunc@erat.edu'),( 'Germane','Jackson','Cras.dolor@purus.com'),( 'Cassidy','Alec','blandit.mattis@luctusCurabitur.net'),( 'Karly','Denton','ornare@Nullaaliquet.ca'),( 'Tara','Brett','a.purus.Duis@euismodetcommodo.edu'),( 'Talon','Nero','ornare.In@velarcu.com'),( 'Cyrus','Otto','et.magnis@velitPellentesque.com'),( 'Logan','Elvis','vel.nisl@turpisNulla.org');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Abigail','Benedict','diam.Proin@Aeneaneget.net'),( 'Ifeoma','Uriel','mauris.sagittis.placerat@interdumliberodui.org'),( 'Pandora','Harrison','lorem.semper.auctor@infaucibus.com'),( 'Maggie','Damian','mattis@magna.edu'),( 'Maia','Dexter','nulla.Cras@tristique.com'),( 'Zeph','August','sollicitudin.commodo.ipsum@tempuslorem.com'),( 'Tyrone','Dane','mi.tempor.lorem@utlacus.edu'),( 'Pandora','Abbot','malesuada.id@ultricesiaculis.co.uk'),( 'Honorato','Moses','felis.purus@ridiculusmusProin.net'),( 'Tashya','Kermit','Donec.at@etrutrum.net');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Beck','Quinn','amet.consectetuer.adipiscing@malesuadautsem.net'),( 'TaShya','Jarrod','massa.lobortis@cursus.org'),( 'Chester','Linus','ante@idblanditat.edu'),( 'Hilel','Mason','aliquet.vel.vulputate@pedeet.net'),( 'Athena','Ivor','metus.sit@fringilla.com'),( 'Risa','Troy','Integer.urna@aliquam.edu'),( 'Dexter','Zahir','est@Praesent.ca'),( 'Rooney','Neil','Nullam.vitae.diam@FuscemollisDuis.com'),( 'Peter','Jarrod','tellus.Nunc.lectus@tortorInteger.com'),( 'Maggy','Murphy','rhoncus.Proin.nisl@blandit.com');
INSERT INTO Utilisateur ( nom,prenom,mail) VALUES ( 'Avye','Damon','id.ante@velturpisAliquam.edu'),( 'Aspen','Byron','massa.Quisque.porttitor@facilisis.edu'),( 'Amity','Byron','vulputate.dui@turpis.org'),( 'Idona','Lance','vulputate.ullamcorper@Aliquam.ca'),( 'Sonia','Jakeem','ornare@Praesentinterdum.edu'),( 'Abdul','Jamal','Phasellus@cursusInteger.edu'),( 'Xena','Mannix','ornare@sapien.com'),( 'Keaton','Denton','arcu.imperdiet.ullamcorper@conubianostraper.org'),( 'Xerxes','Ulysses','sed@ipsum.net'),( 'Lysandra','Wayne','nisi.Mauris.nulla@Cumsociis.edu');

disconnect;
exit;
